# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Package documentation - check build

on:
  push:
    branches: [ main, dev, test, prod, develop, release ]
  pull_request:
    branches: [ main, dev, test, prod, develop, release ]

jobs:
  build:

    runs-on: ubuntu-latest  # Alternative: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        pip install flake8 pytest pytest-cov sphinx==5.3.0 sphinx_rtd_theme==1.1.1
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        # Options: --ignore=tests/specific.py --ignore-glob=tests/ignore-pattern
        pytest -rEf tests/unit/ --cov macrosynergy -p no:warnings --verbose --cov macrosynergy
    - name: Upload coverage reports to Codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}
    - name: Test sphinx build of documentation
      run: |
        pip install -r docs/requirements.txt
        python -m docs/build_md.py